bool proxyStatus = false;
const String IP_URL = "ip_url" ;

const String USER_ID = "userId";
const String PERSON_TYPE = "personType";
const String PERSON_NAME = "personName";
const String GROUP = "group";
const String ASSIGNED = "assigned";
const String COVERED = "covered";
const String PRODUCTIVE = "productive";
const String CANOLA = "canola";
const String OLIVE = "olive";
const String GOLD = "gold";
const String SUNFLOWER = "sunflower";
const String SOYABEAN = "SOYABEAN";
const String COTTONSEED = "cottonseed";
const String TARGET = "target";
const String BEAT_ID = "beat_id";
const String BEAT_NAME = "beat_name";
const String DISTANCE_ALLOWED = "distanceAllowed";
const String ATT_STATUS = "attendance_status";
const String SHOP_NAME = "shop_name";
const String SHOP_ID = "shop_id";
const String ADDRESS = "address";
const String STATE = "state";
const String ZONE = "zone";
const String AREA = "area";
const String PINCODE = "pincode";
const String CONTACT_PERSON = "contact_person";
const String MOBILE_NUMBER = "mobile";
const String SHOP_TYPE = "shop_type";
const String CATEGORY = "category";
const String SHOPGROUP = "shop_group";
const String app_name = 'DSR';
const String dashboard = 'My Dashboard';
const String appTitle = 'Drawer Demo';
const String latitude = 'latitude';
const String longitude = 'longitude';
const String address = 'address';

bool present = true, hd = true, wo = true,eod = true ,ab =true;
bool penabled = true,hdenabled = true,woenabled = true,eodenabled = true,abenabled= true;
